### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by adfsagaafdfasadfsadfs** [Luis729/reddit-eclipse-bot#6]
`+available`

Our rules state that people who are not available should opt out of wars (red shield). However, when people go on vacation, mandatory wars can override the red shield. Hence, we need an availability factor that checks who is available or not.

This command sends a list of people who are available or not. This list will show anyone who is green in Clash of Clans (if possible) and is not on vacation. People will generally let **Leadership** know they are on vacation.

There will be a variant `+available override` that will override all red shields, but not override anyone who is in vacation - no vacation should ever be ruined.

An expiration date would work very well with this command, storing it in a data sheet would work, as changes to the sheet will be very small.

**Comment by Luis729** [comment]
For information: testing issues functionality in GitHub, as well as introducing a new feature request for the bot

**Comment by Luis729** [comment]
Decided this is unnecessary.
